import React, { useState, useEffect } from 'react';
import { Sun, Moon, Check, ChevronDown } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

// ── Supabase client (uses your autogenerated credentials) ──
const projectId = "szmfxbcvcumnzbxffmro";
const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6bWZ4YmN2Y3VtbnpieGZmbXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzNjQzNjYsImV4cCI6MjA5MTk0MDM2Nn0.ACiZUqAVpn2m4tSt2uwFK-asxSaho0iRkoqagZjK9-g";
const supabase = createClient(`https://${projectId}.supabase.co`, publicAnonKey);

// ── Resend API key — move to .env as VITE_RESEND_API_KEY after testing ──
const RESEND_API_KEY = import.meta.env.VITE_RESEND_API_KEY ?? '';

export default function Contact() {
  const [theme, setTheme] = useState<'light' | 'dark'>('light');
  const [formSubmitted, setFormSubmitted] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    email: '',
    company: '',
    jobTitle: '',
    callVolume: '',
    telephonyStack: '',
    notes: ''
  });

  useEffect(() => {
    const saved = localStorage.getItem('relay-theme');
    if (saved === 'dark' || saved === 'light') setTheme(saved);
  }, []);

  const toggleTheme = () => {
    const newTheme = theme === 'light' ? 'dark' : 'light';
    setTheme(newTheme);
    localStorage.setItem('relay-theme', newTheme);
  };

  const colors = theme === 'light' ? {
    bg: '#ffffff',
    bg2: '#f5f5f5',
    text: '#0a0a0f',
    text2: '#6b6b7b',
    text3: '#9a9aaa',
    blue: '#2B5BE8',
    blueH: '#1A3FCC',
    border: '#e5e5ea',
    border2: '#d0d0da',
    navBg: 'rgba(255,255,255,0.92)',
    navBorder: '#e5e5ea',
  } : {
    bg: '#0a0a0f',
    bg2: '#1a1a1f',
    text: '#f0f0f4',
    text2: '#a0a0b0',
    text3: '#505060',
    blue: '#4a7aff',
    blueH: '#6b94ff',
    border: 'rgba(255,255,255,0.07)',
    border2: 'rgba(255,255,255,0.13)',
    navBg: 'rgba(10,10,15,0.9)',
    navBorder: 'rgba(255,255,255,0.07)',
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setSubmitError(null);

    try {
      // ── 1. Save lead to Supabase ──
      const { error: dbError } = await supabase.from('leads').insert({
        first_name:       formData.firstName,
        last_name:        formData.lastName,
        email:            formData.email,
        company:          formData.company,
        job_title:        formData.jobTitle,
        call_volume:      formData.callVolume,
        telephony_stack:  formData.telephonyStack,
        notes:            formData.notes,
      });

      if (dbError) throw new Error(`Database error: ${dbError.message}`);

      // ── 2. Send notification email via Resend ──
      if (RESEND_API_KEY) {
        const emailRes = await fetch('https://api.resend.com/emails', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${RESEND_API_KEY}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            from: 'Relay Contact Form <noreply@getrelay.now>',
            to: 'michael@getrelay.now',
            subject: `New design partner request — ${formData.company}`,
            html: `
              <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 32px; background: #0a0a0f; color: #f0f0f4; border-radius: 8px;">
                <div style="margin-bottom: 24px; padding-bottom: 24px; border-bottom: 1px solid rgba(255,255,255,0.1);">
                  <p style="font-size: 11px; letter-spacing: 0.12em; text-transform: uppercase; color: #4a7aff; margin: 0 0 8px 0; font-family: monospace;">RELAY — NEW LEAD</p>
                  <h1 style="font-size: 24px; font-weight: 800; margin: 0; letter-spacing: -0.02em;">
                    ${formData.firstName} ${formData.lastName}
                  </h1>
                  <p style="margin: 4px 0 0; color: rgba(255,255,255,0.5); font-size: 14px;">${formData.company}</p>
                </div>
                <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
                  ${[
                    ['Email',           formData.email],
                    ['Job Title',       formData.jobTitle],
                    ['Daily Call Volume', formData.callVolume || 'Not specified'],
                    ['Telephony Stack', formData.telephonyStack || 'Not specified'],
                  ].map(([label, value]) => `
                    <tr>
                      <td style="padding: 10px 0; color: rgba(255,255,255,0.4); font-family: monospace; font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase; width: 160px; vertical-align: top;">${label}</td>
                      <td style="padding: 10px 0; color: #f0f0f4;">${value}</td>
                    </tr>
                  `).join('')}
                  ${formData.notes ? `
                    <tr>
                      <td style="padding: 10px 0; color: rgba(255,255,255,0.4); font-family: monospace; font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase; vertical-align: top;">Notes</td>
                      <td style="padding: 10px 0; color: #f0f0f4; line-height: 1.6;">${formData.notes}</td>
                    </tr>
                  ` : ''}
                </table>
                <div style="margin-top: 32px; padding-top: 24px; border-top: 1px solid rgba(255,255,255,0.1);">
                  <a href="https://szmfxbcvcumnzbxffmro.supabase.co" style="display: inline-block; padding: 10px 20px; background: #2B5BE8; color: #fff; text-decoration: none; font-size: 13px; font-weight: 500; border-radius: 4px;">View in Supabase →</a>
                </div>
              </div>
            `,
          }),
        });

        // Log but don't block on email failure — the lead is already saved
        if (!emailRes.ok) {
          console.warn('Resend notification failed:', await emailRes.text());
        }
      }

      setFormSubmitted(true);

    } catch (err) {
      console.error('Form submission error:', err);
      setSubmitError('Something went wrong. Please email us directly at michael@getrelay.now');
    } finally {
      setIsSubmitting(false);
    }
  };

  // ── Input shared style helper ──
  const inputStyle: React.CSSProperties = {
    fontFamily: 'Geist, sans-serif',
    fontSize: '14px',
    padding: '12px 16px',
    border: `1px solid ${colors.border}`,
    borderRadius: '0',
    background: colors.bg,
    color: colors.text,
    transition: 'border-color 0.2s',
    outline: 'none',
    width: '100%',
  };

  return (
    <div style={{ backgroundColor: colors.bg, minHeight: '100vh', transition: 'background 0.3s, color 0.3s' }}>
      <style>{`
        @media (max-width: 768px) {
          .contact-layout { flex-direction: column !important; }
          .contact-left { width: 100% !important; padding: 40px 24px !important; min-height: auto !important; }
          .contact-left .benefits-section { display: none !important; }
          .contact-left .contact-info-section { display: none !important; }
          .contact-right { padding: 40px 24px !important; border-left: none !important; border-top: 1px solid ${colors.border} !important; }
        }
      `}</style>

      {/* ── NAV ── */}
      <nav style={{
        position: 'fixed', top: 0, left: 0, right: 0, zIndex: 300,
        height: '60px', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '0 48px', background: colors.navBg,
        backdropFilter: 'blur(20px)', WebkitBackdropFilter: 'blur(20px)',
        borderBottom: `1px solid ${colors.navBorder}`, transition: 'background 0.3s, border-color 0.3s'
      }}>
        <a href="/" style={{ display: 'flex', alignItems: 'center', gap: '10px', fontFamily: 'Geist, sans-serif', fontWeight: 700, fontSize: '17px', letterSpacing: '-0.4px', color: colors.text, textDecoration: 'none', flexShrink: 0 }}>
          <div style={{ width: '28px', height: '28px', position: 'relative', flexShrink: 0 }}>
            <div style={{ width: '28px', height: '28px', borderRadius: '50%', border: '2.5px solid transparent', background: 'linear-gradient(135deg, #1A3FCC, #4a7aff, #7aa0ff, #1A3FCC) border-box', WebkitMask: 'linear-gradient(#fff 0 0) padding-box, linear-gradient(#fff 0 0)', WebkitMaskComposite: 'destination-out', maskComposite: 'exclude', position: 'absolute', inset: 0, transform: 'rotate(-20deg) scaleX(0.55)' }} />
            <div style={{ width: '8px', height: '8px', background: colors.text3, borderRadius: '50%', position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%,-50%)' }} />
          </div>
          RELAY
        </a>

        <ul style={{ display: 'flex', gap: '28px', listStyle: 'none', alignItems: 'center' }}>
          {[{ href: '/#problem', label: 'Problem' }, { href: '/#how', label: 'How It Works' }, { href: '/#features', label: 'Features' }, { href: '/#roadmap', label: 'Roadmap' }, { href: '/#who', label: "Who It's For" }].map(link => (
            <li key={link.href} className="hidden md:block">
              <a href={link.href} style={{ fontSize: '13px', color: colors.text2, textDecoration: 'none', transition: 'color 0.2s', whiteSpace: 'nowrap' }} onMouseEnter={e => e.currentTarget.style.color = colors.text} onMouseLeave={e => e.currentTarget.style.color = colors.text2}>{link.label}</a>
            </li>
          ))}
        </ul>

        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexShrink: 0 }}>
          <button onClick={toggleTheme} style={{ width: '36px', height: '36px', border: `1px solid ${colors.border2}`, background: 'transparent', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '6px', color: colors.text2 }}>
            {theme === 'light' ? <Sun size={16} /> : <Moon size={16} />}
          </button>
          <a href="/contact" style={{ fontFamily: 'Geist, sans-serif', fontSize: '13px', fontWeight: 500, color: '#fff', background: colors.blue, padding: '8px 18px', textDecoration: 'none', whiteSpace: 'nowrap' }}
            onMouseEnter={e => { e.currentTarget.style.background = colors.blueH; e.currentTarget.style.transform = 'translateY(-1px)'; }}
            onMouseLeave={e => { e.currentTarget.style.background = colors.blue; e.currentTarget.style.transform = 'translateY(0)'; }}>
            Request Access
          </a>
          <button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} className="md:hidden" style={{ width: '36px', height: '36px', background: 'transparent', border: `1px solid ${colors.border2}`, cursor: 'pointer', borderRadius: '6px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '5px' }}>
            <span style={{ display: 'block', width: '18px', height: '1.5px', background: colors.text2, borderRadius: '2px', transition: 'all 0.25s ease', transform: mobileMenuOpen ? 'translateY(6.5px) rotate(45deg)' : 'none' }} />
            <span style={{ display: 'block', width: '18px', height: '1.5px', background: colors.text2, borderRadius: '2px', transition: 'all 0.25s ease', opacity: mobileMenuOpen ? 0 : 1 }} />
            <span style={{ display: 'block', width: '18px', height: '1.5px', background: colors.text2, borderRadius: '2px', transition: 'all 0.25s ease', transform: mobileMenuOpen ? 'translateY(-6.5px) rotate(-45deg)' : 'none' }} />
          </button>
        </div>
      </nav>

      {mobileMenuOpen && (
        <div style={{ position: 'fixed', top: '60px', left: 0, right: 0, zIndex: 299, background: colors.navBg, backdropFilter: 'blur(20px)', borderBottom: `1px solid ${colors.navBorder}`, padding: '16px 24px 24px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
          {[{ href: '/#problem', label: 'Problem' }, { href: '/#how', label: 'How It Works' }, { href: '/#features', label: 'Features' }, { href: '/#roadmap', label: 'Roadmap' }, { href: '/#who', label: "Who It's For" }].map(link => (
            <a key={link.href} href={link.href} onClick={() => setMobileMenuOpen(false)} style={{ fontSize: '15px', color: colors.text2, textDecoration: 'none', padding: '10px 0', borderBottom: `1px solid ${colors.border}` }}>{link.label}</a>
          ))}
          <a href="/contact" onClick={() => setMobileMenuOpen(false)} style={{ marginTop: '12px', display: 'block', textAlign: 'center', fontWeight: 500, fontSize: '14px', color: '#fff', background: colors.blue, padding: '12px' }}>Request Access</a>
        </div>
      )}

      {/* ── MAIN LAYOUT ── */}
      <div className="contact-layout" style={{ paddingTop: '60px', minHeight: 'calc(100vh - 60px)', display: 'flex' }}>

        {/* Left panel — always dark */}
        <div className="contact-left" style={{ width: '45%', background: '#080f1e', padding: '80px 60px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', position: 'relative', overflow: 'hidden' }}>
          <div style={{ position: 'absolute', top: '-10%', left: '50%', transform: 'translateX(-50%)', width: '500px', height: '400px', background: 'radial-gradient(ellipse, rgba(74,122,255,0.15) 0%, transparent 70%)', pointerEvents: 'none' }} />
          <div style={{ position: 'relative', zIndex: 2 }}>
            <div style={{ marginBottom: '60px' }}>
              <div style={{ fontFamily: 'Geist Mono, monospace', fontSize: '10px', fontWeight: 500, letterSpacing: '0.12em', color: '#4a7aff', marginBottom: '24px' }}>— EARLY ACCESS</div>
              <h1 style={{ fontFamily: 'Geist, sans-serif', fontWeight: 800, fontSize: '48px', letterSpacing: '-0.02em', color: '#ffffff', lineHeight: '1.1', marginBottom: '20px' }}>Let&apos;s build this<br />together.</h1>
              <p style={{ fontSize: '16px', color: 'rgba(255,255,255,0.5)', lineHeight: '1.7' }}>We&apos;re signing our first design partners now — contact centers willing to run Relay alongside their existing stack and measure the difference. No cost. Direct product input.</p>
            </div>
            <div className="benefits-section" style={{ display: 'flex', flexDirection: 'column', gap: '0' }}>
              {['White-glove onboarding — we configure Relay for your stack', 'Zero cost during the pilot period', 'Direct line to the product team — your feedback shapes the roadmap', 'AHT before/after measurement — we will show you the data', 'Preferential pricing at commercial launch'].map((benefit, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '12px', padding: '16px 0', borderBottom: i < 4 ? '1px solid rgba(255,255,255,0.06)' : 'none' }}>
                  <div style={{ width: '18px', height: '18px', borderRadius: '50%', background: '#4a7aff', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: '2px' }}>
                    <Check size={11} color="#fff" strokeWidth={3} />
                  </div>
                  <div style={{ fontSize: '13px', color: 'rgba(255,255,255,0.65)', lineHeight: '1.6' }}>{benefit}</div>
                </div>
              ))}
            </div>
          </div>
          <div className="contact-info-section" style={{ position: 'relative', zIndex: 2 }}>
            <div style={{ fontFamily: 'Geist Mono, monospace', fontSize: '9px', fontWeight: 500, letterSpacing: '0.12em', color: 'rgba(255,255,255,0.3)', marginBottom: '12px' }}>CONTACT</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <a href="mailto:michael@getrelay.now" style={{ fontFamily: 'Geist, sans-serif', fontSize: '15px', fontWeight: 500, color: '#ffffff', textDecoration: 'none' }}>michael@getrelay.now</a>
              <div style={{ fontFamily: 'Geist, sans-serif', fontSize: '13px', color: 'rgba(255,255,255,0.4)' }}>Vancouver, BC</div>
            </div>
          </div>
        </div>

        {/* Right panel — form */}
        <div className="contact-right" style={{ flex: 1, background: colors.bg, padding: '80px', display: 'flex', flexDirection: 'column', justifyContent: 'center', borderLeft: `1px solid ${colors.border}` }}>
          {!formSubmitted ? (
            <div style={{ maxWidth: '600px', margin: '0 auto', width: '100%' }}>
              <div style={{ marginBottom: '40px' }}>
                <div style={{ fontFamily: 'Geist Mono, monospace', fontSize: '10px', fontWeight: 500, letterSpacing: '0.12em', color: colors.blue, marginBottom: '16px' }}>— REQUEST ACCESS</div>
                <h2 style={{ fontFamily: 'Geist, sans-serif', fontWeight: 700, fontSize: '28px', color: colors.text, marginBottom: '8px' }}>Tell us about your operation.</h2>
                <p style={{ fontSize: '14px', color: colors.text2 }}>We&apos;ll follow up within one business day to set up a call.</p>
              </div>

              <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                  <input type="text" name="firstName" placeholder="First Name" required value={formData.firstName} onChange={handleChange} style={inputStyle} onFocus={e => e.currentTarget.style.borderColor = colors.blue} onBlur={e => e.currentTarget.style.borderColor = colors.border} />
                  <input type="text" name="lastName" placeholder="Last Name" required value={formData.lastName} onChange={handleChange} style={inputStyle} onFocus={e => e.currentTarget.style.borderColor = colors.blue} onBlur={e => e.currentTarget.style.borderColor = colors.border} />
                </div>
                <input type="email" name="email" placeholder="Work Email" required value={formData.email} onChange={handleChange} style={inputStyle} onFocus={e => e.currentTarget.style.borderColor = colors.blue} onBlur={e => e.currentTarget.style.borderColor = colors.border} />
                <input type="text" name="company" placeholder="Company / Organization" required value={formData.company} onChange={handleChange} style={inputStyle} onFocus={e => e.currentTarget.style.borderColor = colors.blue} onBlur={e => e.currentTarget.style.borderColor = colors.border} />
                <input type="text" name="jobTitle" placeholder="Job Title" required value={formData.jobTitle} onChange={handleChange} style={inputStyle} onFocus={e => e.currentTarget.style.borderColor = colors.blue} onBlur={e => e.currentTarget.style.borderColor = colors.border} />

                <div style={{ position: 'relative' }}>
                  <select name="callVolume" required value={formData.callVolume} onChange={handleChange} style={{ ...inputStyle, paddingRight: '40px', appearance: 'none', cursor: 'pointer', color: formData.callVolume ? colors.text : colors.text2 }} onFocus={e => e.currentTarget.style.borderColor = colors.blue} onBlur={e => e.currentTarget.style.borderColor = colors.border}>
                    <option value="">Daily Call Volume</option>
                    <option value="under-500">Under 500</option>
                    <option value="500-2000">500–2,000</option>
                    <option value="2000-10000">2,000–10,000</option>
                    <option value="over-10000">Over 10,000</option>
                  </select>
                  <ChevronDown size={16} style={{ position: 'absolute', right: '16px', top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none', color: colors.text2 }} />
                </div>

                <div style={{ position: 'relative' }}>
                  <select name="telephonyStack" required value={formData.telephonyStack} onChange={handleChange} style={{ ...inputStyle, paddingRight: '40px', appearance: 'none', cursor: 'pointer', color: formData.telephonyStack ? colors.text : colors.text2 }} onFocus={e => e.currentTarget.style.borderColor = colors.blue} onBlur={e => e.currentTarget.style.borderColor = colors.border}>
                    <option value="">Current Telephony Stack</option>
                    <option value="twilio">Twilio</option>
                    <option value="genesys">Genesys</option>
                    <option value="avaya">Avaya</option>
                    <option value="cisco">Cisco</option>
                    <option value="amazon-connect">Amazon Connect</option>
                    <option value="five9">Five9</option>
                    <option value="other">Other</option>
                  </select>
                  <ChevronDown size={16} style={{ position: 'absolute', right: '16px', top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none', color: colors.text2 }} />
                </div>

                <textarea name="notes" placeholder="Current AHT, main pain point, specific use case..." value={formData.notes} onChange={handleChange} style={{ ...inputStyle, minHeight: '100px', resize: 'vertical' }} onFocus={e => e.currentTarget.style.borderColor = colors.blue} onBlur={e => e.currentTarget.style.borderColor = colors.border} />

                {/* Error message */}
                {submitError && (
                  <div style={{ padding: '12px 16px', background: 'rgba(220,38,38,0.08)', border: '1px solid rgba(220,38,38,0.2)', color: '#dc2626', fontSize: '13px', lineHeight: '1.5' }}>
                    {submitError}
                  </div>
                )}

                <button
                  type="submit"
                  disabled={isSubmitting}
                  style={{ fontFamily: 'Geist, sans-serif', fontSize: '14px', fontWeight: 500, color: '#fff', background: isSubmitting ? colors.text3 : colors.blue, padding: '14px 0', border: 'none', borderRadius: '0', cursor: isSubmitting ? 'not-allowed' : 'pointer', transition: 'all 0.2s', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}
                  onMouseEnter={e => { if (!isSubmitting) { e.currentTarget.style.background = colors.blueH; e.currentTarget.style.transform = 'translateY(-1px)'; e.currentTarget.style.boxShadow = '0 4px 12px rgba(43,91,232,0.3)'; }}}
                  onMouseLeave={e => { e.currentTarget.style.background = isSubmitting ? colors.text3 : colors.blue; e.currentTarget.style.transform = 'translateY(0)'; e.currentTarget.style.boxShadow = 'none'; }}
                >
                  {isSubmitting ? 'Sending...' : 'Send Request →'}
                </button>

                <div style={{ textAlign: 'center', fontFamily: 'Geist Mono, monospace', fontSize: '10px', color: colors.text3, letterSpacing: '0.04em' }}>
                  No commitment required · Design partner slots limited · Built in Vancouver, BC
                </div>
              </form>
            </div>
          ) : (
            /* Success state */
            <div style={{ maxWidth: '500px', margin: '0 auto', textAlign: 'center' }}>
              <div style={{ width: '48px', height: '48px', borderRadius: '50%', background: colors.blue, display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 24px' }}>
                <Check size={24} color="#fff" strokeWidth={3} />
              </div>
              <h2 style={{ fontFamily: 'Geist, sans-serif', fontWeight: 700, fontSize: '20px', color: colors.text, marginBottom: '12px' }}>Request received.</h2>
              <p style={{ fontSize: '14px', color: colors.text2, lineHeight: '1.6' }}>
                We&apos;ll be in touch within one business day. In the meantime, explore the{' '}
                <a href="/#roadmap" style={{ color: colors.blue, textDecoration: 'none' }}>roadmap</a>
                {' '}or{' '}
                <a href="/#features" style={{ color: colors.blue, textDecoration: 'none' }}>feature list</a>.
              </p>
            </div>
          )}
        </div>
      </div>

      {/* ── FOOTER ── */}
      <footer style={{ borderTop: `1px solid ${colors.border}`, padding: '28px 48px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px', background: colors.bg }}>
        <a href="/" style={{ fontFamily: 'Geist, sans-serif', fontWeight: 700, fontSize: '15px', letterSpacing: '-0.3px', color: colors.text, display: 'flex', alignItems: 'center', gap: '8px', textDecoration: 'none' }}>
          <div style={{ width: '20px', height: '20px', position: 'relative' }}>
            <div style={{ width: '20px', height: '20px', borderRadius: '50%', border: '2px solid transparent', background: 'linear-gradient(135deg, #1A3FCC, #4a7aff, #7aa0ff, #1A3FCC) border-box', WebkitMask: 'linear-gradient(#fff 0 0) padding-box, linear-gradient(#fff 0 0)', WebkitMaskComposite: 'destination-out', maskComposite: 'exclude', position: 'absolute', inset: 0, transform: 'rotate(-20deg) scaleX(0.55)' }} />
            <div style={{ width: '6px', height: '6px', background: colors.text3, borderRadius: '50%', position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%,-50%)' }} />
          </div>
          RELAY
        </a>
        <div style={{ fontFamily: 'Geist Mono, monospace', fontSize: '10px', color: colors.text3, letterSpacing: '0.04em' }}>© 2025 Relay Technologies Inc. · Vancouver, BC</div>
        <ul style={{ display: 'flex', gap: '20px', listStyle: 'none' }}>
          {[{ href: '/contact', label: 'Contact' }, { href: '/#roadmap', label: 'Roadmap' }, { href: '/', label: 'Home' }].map(link => (
            <li key={link.href}>
              <a href={link.href} style={{ fontFamily: 'Geist Mono, monospace', fontSize: '10px', letterSpacing: '0.08em', textTransform: 'uppercase', color: colors.text3, textDecoration: 'none', transition: 'color 0.2s' }} onMouseEnter={e => e.currentTarget.style.color = colors.blue} onMouseLeave={e => e.currentTarget.style.color = colors.text3}>{link.label}</a>
            </li>
          ))}
        </ul>
      </footer>
    </div>
  );
}
